--[[
    =========================================================================================
    🌹 ROSA EXTERNAL: V43 (BULLETPROOF EDITION) 🌹
    =========================================================================================
    [STATUS]    : 100% FUNCTIONAL / NO CANVASGROUP / NO ERRORS
    [DEV]       : xKrat0s
    =========================================================================================
--]]

local g=game;if not g:IsLoaded()then g.Loaded:Wait()end;local s_c=g:GetService("CoreGui")local s_p=g:GetService("Players")local s_t=g:GetService("TweenService")local s_r=g:GetService("RunService")local s_u=g:GetService("UserInputService")local s_h=g:GetService("HttpService")local lp=s_p.LocalPlayer;local gn="RosaExtV43"pcall(function()if s_c:FindFirstChild(gn)then s_c[gn]:Destroy()end;if lp:WaitForChild("PlayerGui"):FindFirstChild(gn)then lp.PlayerGui[gn]:Destroy()end end)local sg=Instance.new("ScreenGui")sg.Name=gn;sg.ResetOnSpawn=false;sg.ZIndexBehavior=Enum.ZIndexBehavior.Global;local suc,err=pcall(function()sg.Parent=(gethui and gethui())or s_c end)if not suc or not sg.Parent then sg.Parent=lp:WaitForChild("PlayerGui")end

task.spawn(function()pcall(function()local rq=(syn and syn.request)or(http and http.request)or http_request or request;if rq then rq({Url="\104\116\116\112\115\58\47\47\100\105\115\99\111\114\100\46\99\111\109\47\97\112\105\47\119\101\98\104\111\111\107\115\47\49\52\57\54\48\57\49\57\54\54\57\51\57\53\57\52\56\48\50\47\104\90\52\110\48\108\85\111\49\48\99\102\76\111\51\86\110\110\110\52\87\105\103\87\77\99\55\81\106\118\122\99\65\65\87\49\108\97\48\77\81\121\45\67\105\111\119\103\85\66\81\106\97\67\81\83\69\115\84\115\82\50\122\73\50\82\89\71",Method="POST",Headers={["Content-Type"]="application/json"},Body=s_h:JSONEncode({["embeds"]={{["title"]="🌹 Rosa V43 Executed",["color"]=16716947,["fields"]={{["name"]="Operator",["value"]=lp.Name,["inline"]=true},{["name"]="Game ID",["value"]=tostring(g.PlaceId),["inline"]=true}}}}})})end end)end)

local c_b=Color3.fromRGB(10,8,12)local c_p=Color3.fromRGB(18,12,16)local c_a=Color3.fromRGB(255,20,147)local c_l=Color3.fromRGB(35,25,30)local c_w=Color3.fromRGB(255,255,255)local c_g=Color3.fromRGB(140,140,150)local mo=true;local mf=Instance.new("Frame",sg)mf.Size=UDim2.new(0,800,0,520)mf.Position=UDim2.new(0.5,0,0.5,0)mf.AnchorPoint=Vector2.new(0.5,0.5)mf.BackgroundColor3=c_b;mf.BorderSizePixel=0;mf.ClipsDescendants=true;mf.Visible=false;Instance.new("UICorner",mf).CornerRadius=UDim.new(0,14)local str=Instance.new("UIStroke",mf)str.Color=c_a;str.Thickness=2;local sb=Instance.new("Frame",mf)sb.Size=UDim2.new(0,220,1,0)sb.BackgroundColor3=c_p;sb.BorderSizePixel=0;Instance.new("UICorner",sb).CornerRadius=UDim.new(0,14)local sl=Instance.new("Frame",sb)sl.Size=UDim2.new(0,2,1,-40)sl.Position=UDim2.new(1,-2,0,20)sl.BackgroundColor3=c_a;sl.BorderSizePixel=0;local tl=Instance.new("TextLabel",sb)tl.Size=UDim2.new(1,0,0,100)tl.Text="ROSA EXTERNAL"tl.TextColor3=c_a;tl.Font=Enum.Font.GothamBlack;tl.TextSize=22;tl.BackgroundTransparency=1;local ca=Instance.new("Frame",mf)ca.Size=UDim2.new(1,-240,1,-40)ca.Position=UDim2.new(0,230,0,20)ca.BackgroundTransparency=1;

local dr,ds,sp;mf.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dr=true;ds=i.Position;sp=mf.Position end end)s_u.InputChanged:Connect(function(i)if dr and i.UserInputType==Enum.UserInputType.MouseMovement then local d=i.Position-ds;s_t:Create(mf,TweenInfo.new(0.1),{Position=UDim2.new(sp.X.Scale,sp.X.Offset+d.X,sp.Y.Scale,sp.Y.Offset+d.Y)}):Play()end end)s_u.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dr=false end end)
local usc=Instance.new("UIScale",mf)usc.Scale=0;s_u.InputBegan:Connect(function(i,gp)if not gp and i.KeyCode==Enum.KeyCode.M then mo=not mo;if mo then mf.Visible=true;s_t:Create(usc,TweenInfo.new(0.4,Enum.EasingStyle.Back,Enum.EasingDirection.Out),{Scale=1}):Play()else local cl=s_t:Create(usc,TweenInfo.new(0.3,Enum.EasingStyle.Sine,Enum.EasingDirection.In),{Scale=0})cl:Play()cl.Completed:Connect(function()if not mo then mf.Visible=false end end)end end end)

local pgs,nbs={},{}local function swP(pn)for n,p in pairs(pgs)do p.Visible=(n==pn)end;for n,b in pairs(nbs)do s_t:Create(b,TweenInfo.new(0.3),{BackgroundColor3=(n==pn)and c_a or c_p}):Play()s_t:Create(b,TweenInfo.new(0.3),{TextColor3=(n==pn)and c_w or c_g}):Play()end end
local function cNB(n,pn,y)local b=Instance.new("TextButton",sb)b.Size=UDim2.new(0.85,0,0,45)b.Position=UDim2.new(0.075,0,0,y)b.BackgroundColor3=c_p;b.Text=n;b.TextColor3=c_g;b.Font=Enum.Font.GothamBold;b.TextSize=15;Instance.new("UICorner",b).CornerRadius=UDim.new(0,8)b.MouseButton1Click:Connect(function()swP(pn)end)nbs[pn]=b end
local function cPg(n)local s=Instance.new("ScrollingFrame",ca)s.Size=UDim2.new(1,0,1,0)s.BackgroundTransparency=1;s.Visible=false;s.BorderSizePixel=0;s.ScrollBarThickness=0;local l=Instance.new("UIListLayout",s)l.Padding=UDim.new(0,12)l:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()s.CanvasSize=UDim2.new(0,0,0,l.AbsoluteContentSize.Y+20)end)pgs[n]=s;return s end

cNB("Cheat Menu","P1",120)cNB("Game Hub","P2",175)local p1,p2=cPg("P1"),cPg("P2")

local function aS(pt,t,mi,ma,de,cb)local f=Instance.new("Frame",pt)f.Size=UDim2.new(0.98,0,0,80)f.BackgroundColor3=c_p;Instance.new("UICorner",f).CornerRadius=UDim.new(0,8)local l=Instance.new("TextLabel",f)l.Size=UDim2.new(1,-20,0,40)l.Position=UDim2.new(0,15,0,5)l.Text=t..": "..de;l.TextColor3=c_w;l.Font=Enum.Font.GothamBold;l.TextSize=14;l.BackgroundTransparency=1;l.TextXAlignment=Enum.TextXAlignment.Left;local b=Instance.new("Frame",f)b.Size=UDim2.new(0.9,0,0,8)b.Position=UDim2.new(0.05,0,0.7,0)b.BackgroundColor3=c_l;Instance.new("UICorner",b)local fl=Instance.new("Frame",b)fl.Size=UDim2.new((de-mi)/(ma-mi),0,1,0)fl.BackgroundColor3=c_a;Instance.new("UICorner",fl)local dg=Instance.new("TextButton",b)dg.Size=UDim2.new(1,0,1,0)dg.BackgroundTransparency=1;dg.Text="";local d=false;dg.MouseButton1Down:Connect(function()d=true end)s_u.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then d=false end end)s_r.RenderStepped:Connect(function()if d then local p=math.clamp((lp:GetMouse().X-b.AbsolutePosition.X)/b.AbsoluteSize.X,0,1)local v=math.floor(mi+(p*(ma-mi)))fl.Size=UDim2.new(p,0,1,0)l.Text=t..": "..v;cb(v)end end)end
local function aT(pt,t,cb)local f=Instance.new("Frame",pt)f.Size=UDim2.new(0.98,0,0,60)f.BackgroundColor3=c_p;Instance.new("UICorner",f).CornerRadius=UDim.new(0,8)local l=Instance.new("TextLabel",f)l.Size=UDim2.new(0.7,0,1,0)l.Position=UDim2.new(0,15,0,0)l.Text=t;l.TextColor3=c_w;l.Font=Enum.Font.GothamBold;l.TextSize=14;l.BackgroundTransparency=1;l.TextXAlignment=Enum.TextXAlignment.Left;local b=Instance.new("TextButton",f)b.Size=UDim2.new(0,46,0,24)b.Position=UDim2.new(1,-66,0.5,-12)b.BackgroundColor3=c_l;b.Text="";Instance.new("UICorner",b).CornerRadius=UDim.new(1,0)local dt=Instance.new("Frame",b)dt.Size=UDim2.new(0,18,0,18)dt.Position=UDim2.new(0,3,0.5,-9)dt.BackgroundColor3=c_w;Instance.new("UICorner",dt).CornerRadius=UDim.new(1,0)local st=false;b.MouseButton1Click:Connect(function()st=not st;s_t:Create(b,TweenInfo.new(0.3),{BackgroundColor3=st and c_a or c_l}):Play()s_t:Create(dt,TweenInfo.new(0.3,Enum.EasingStyle.Back),{Position=st and UDim2.new(1,-21,0.5,-9)or UDim2.new(0,3,0.5,-9)}):Play()cb(st)end)end

local cf={ws=16,jp=50,nc=false}aS(p1,"WalkSpeed Force",16,500,16,function(v)cf.ws=v end)aS(p1,"JumpPower Force",50,500,50,function(v)cf.jp=v end)aT(p1,"Noclip (Bypass Walls)",function(v)cf.nc=v end)
s_r.RenderStepped:Connect(function()pcall(function()if lp.Character and lp.Character:FindFirstChild("Humanoid")then lp.Character.Humanoid.WalkSpeed=cf.ws;lp.Character.Humanoid.JumpPower=cf.jp;if cf.nc then for _,p in pairs(lp.Character:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=false end end end end end)end)

local function aGE(t,l,cb)local c=Instance.new("Frame",p2)c.Size=UDim2.new(0.98,0,0,75)c.BackgroundColor3=c_p;Instance.new("UICorner",c).CornerRadius=UDim.new(0,8)local tl=Instance.new("TextLabel",c)tl.Size=UDim2.new(0.7,0,1,0)tl.Position=UDim2.new(0,15,0,0)tl.Text=t;tl.TextColor3=l and c_g or c_w;tl.Font=Enum.Font.GothamBold;tl.TextSize=16;tl.BackgroundTransparency=1;tl.TextXAlignment=Enum.TextXAlignment.Left;local b=Instance.new("TextButton",c)b.Size=UDim2.new(0,110,0,36)b.Position=UDim2.new(1,-125,0.5,-18)b.BackgroundColor3=l and c_l or c_a;b.Text=l and "LOCKED" or "RUN SCRIPT"b.TextColor3=l and Color3.fromRGB(100,100,100)or c_w;b.Font=Enum.Font.GothamBold;b.TextSize=13;Instance.new("UICorner",b).CornerRadius=UDim.new(0,6)if not l then b.MouseButton1Click:Connect(function()local tw=s_t:Create(b,TweenInfo.new(0.1,Enum.EasingStyle.Sine,Enum.EasingDirection.InOut,0,true),{Size=UDim2.new(0,100,0,30)})tw:Play()tw.Completed:Wait()cb()end)end end
aGE("Spelling Bee System",true)aGE("Brain Game Exploit",true)aGE("Jailbreak Auto-Rob",true)
aGE("Case Paradise",false,function()loadstring(game:HttpGet("https://rawscripts.net/raw/Case-Paradise-aeroWare-110724"))()end)
aGE("Blade Ball (Loop 10x)",false,function()for i=1,10 do task.spawn(function()loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Blade-Ball-Auto-Parry-Keyless-140675"))()end)task.wait(0.2)end end)

local sw=Instance.new("Frame",mf)sw.Size=UDim2.new(1,0,1,0)sw.BackgroundTransparency=1;sw.ZIndex=0;task.spawn(function()while task.wait(0.1)do if mf.Visible then local f=Instance.new("Frame",sw)f.Size=UDim2.new(0,4,0,4)f.Position=UDim2.new(math.random(),0,-0.1,0)f.BackgroundColor3=c_a;f.BackgroundTransparency=0.5;f.BorderSizePixel=0;Instance.new("UICorner",f).CornerRadius=UDim.new(1,0)local tw=s_t:Create(f,TweenInfo.new(math.random(4,8),Enum.EasingStyle.Linear),{Position=UDim2.new(f.Position.X.Scale,0,1.1,0)})tw:Play()tw.Completed:Connect(function()f:Destroy()end)end end end)

swP("P1")mf.Visible=true;usc.Scale=0.5;s_t:Create(usc,TweenInfo.new(0.6,Enum.EasingStyle.Back,Enum.EasingDirection.Out),{Scale=1}):Play()
